### ISSUE TITLE
Action Mailer-Konfiguration wird ignoriert?

### ISSUE THREAD

**Issue by heikobornholdt** [PingoUPB/PINGOWebApp#14]
Moin,
wenn sich neue Benutzer registrieren, kommt es zu folgenden Fehler

    method=POST path=/users/password format=html controller=devise/passwords action=create status=500 error='ActionView::Template::Error:Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true' duration=132.25 ip=
    vs6.765   2015-01-06T14:50:17.505780+01:00 FATAL
    vs6.765   ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):

In der Datei `config/environments/production.rb` steht:

    config.action_mailer.default_url_options = { :host => 'foo.bar' }

Das wird aber scheinbar ignoriert:

    vagrant@precise64:/vagrant$ RAILS_ENV=production bundle exec rails c
    Loading production environment (Rails 3.2.16)
    irb(main):001:0> Rails.application.config.action_mailer.default_url_options
    => {:host=>""}

**Comment by MichaelWhi** [comment]
Hallo Heiko,
wir können diesen Fehler nicht reproduzieren:
`Rails.application.config.action_mailer.default_url_options` liefert bei uns das gesetzte Hash mit dem Host-Parameter.

Könnten Sie ein mal ganz am Ende der production.rb mittels
`puts "======\n #{Rails.application.config.action_mailer.default_url_options}\n========"` den Wert nach Einlesen der Configdatei anzeigen?
Ist dieser Wert auch leer? Evtl. haben Sie dann den Wert in der Configdatei an anderer Stelle noch mal überschrieben.

Das würde uns hier spontan einfallen… 
Klappt das Senden im Developmentmodus? Hier ist ja auch Localhost als Standard-Mailer-Host eingetragen und sollte bei den Mails berücksichtigt werden.

**Comment by heikobornholdt** [comment]
Hallo Michael,
bei mir liefert Ihre Debug-Zeile den in der Konfiguration gesetzten Wert.
Um einen Fehler durch die reichlichen Anpassungen für die Universität Hamburg auszuschließen, habe ich Ihre Version frisch gezogen und nur die Änderungen vorgenommen, damit die Rails-App ohne Fehlermeldung startet. Sie können die Version hier einsehen: https://github.com/heikobornholdt/PINGOWebApp/tree/default_url_options

Wenn das Problem sich weiterhin nicht produzieren lässt, könnte ich Ihnen meine Vagrant-VM geben. Dort besteht der Fehler.

Gruß

**Comment by heikobornholdt** [comment]
Hallo,
haben Sie sich in den letzten 26 Tagen schon unseren Fehler angucken können?

Gruß

**Comment by MichaelWhi** [comment]
Hallo Heiko,
wir haben in den letzten Wochen bei der Entwicklung auch mehrfach auf Basis dieses Codes neue Server aufgesetzt, wo dieses Problem leider nicht aufgetreten ist. Andere Anwender haben hierüber auch noch kein Feedback gesendet.
Zur Zeit haben wir leider keine Idee, woran es liegen könnte, sorry. Wir haben für nächste Woche noch mal ein paar Tage mit allen Entwicklern zusammen geplant und werden uns hier Ihr Problem noch mal anschauen.

**Comment by heikobornholdt** [comment]
Hallo,
ich habe die Ursache gefunden:

Das Gem "maktoub" überschreibt den ActionMailer-host-Wert mit dem Wert von `Maktoub.home_domain` aus der Datei `config/initializers/maktoub.rb`. WTF! (dies geschieht an der Stelle `maktoub-0.2.5/app/mailers/maktoub/newsletter_mailer.rb:8`).
Da wir keine Newsletter-Funktionalität benötigen, habe ich diese Datei bisher nicht beachtet.

Danke
