### ISSUE TITLE
Latest update

### ISSUE THREAD

**Issue by bazooka720** [PingoUPB/PINGOWebApp#19]
hi...just following-up about the newer release you were planning sometime back. Any update on when it might be done?

**Comment by bazooka720** [comment]
Hi...was just following up on the above request.Please advise?

**Comment by ockhamlabs** [comment]
Any update on this ?

**Comment by lterfloth** [comment]
Hey! First of all, sorry for answering this late. Due to some troubles we are facing with the update, the release will be delayed a little longer. At the moment I can only say that we try to release the update as soon as we know that everything is working as we'd like. Sadly, we don't have a specific releasedate yet. It shouldn't be too long, though.

**Comment by ockhamlabs** [comment]
Thanks. Do you need any help with this? We could commit a bit of resource time potentially? Also, wondering if you are open to releasing the app under any other licensing arrangement?

July 10, 2018 11:26 AM, "lterfloth" <notifications@github.com (mailto:%22lterfloth%22%20<notifications@github.com>)> wrote:
	Hey! First of all, sorry for answering this late. Due to some troubles we are facing with the update, the release will be delayed a little longer. At the moment I can only say that we try to release the update as soon as we know that everything is working as we'd like. Sadly, we don't have a specific releasedate yet. It shouldn't be too long, though.

**Comment by NMarkgraf** [comment]
Well, it is mid 2020 and still no 3.2? -- Is this project still running or ...

**Comment by soumiasari7** [comment]
Hi , is anyone worked on the actuall release and worked for him without problems ?

**Comment by deployn** [comment]
Seems like no updates. Is there an alternative program on Github?
