### ISSUE TITLE
Could not find ruby-standard-deviation-2.0.0 in any of the sources

### ISSUE THREAD

**Issue by soumiasari7** [PingoUPB/PINGOWebApp#21]
when i run bundle install i got this error
`**Could not find ruby-standard-deviation-2.0.0 in any of the sources**`
i tried to search it and install it with gem install but coouldn't find any source
any suggestion ?

**Comment by MichaelWhi** [comment]
Please see #20: You can just comment that gem out in the Gemfile.
Probably you are also not using the most current version, but I am not the maintainer anymore; please wait for answers from them.

**Comment by soumiasari7** [comment]
> 
> 
> Please see #20: You can just comment that gem out in the Gemfile.
> Probably you are also not using the most current version, but I am not the maintainer anymore; please wait for answers from them.

thank you for your quick responce  , i used the recent version and it worked
