### ISSUE TITLE
issue with bundle exec rails server

### ISSUE THREAD

**Issue by soumiasari7** [PingoUPB/PINGOWebApp#22]
Hello All, 
everything work fine with recent version untill i run **bundle exec rails server** to start the app, i got this message bellow 
anyone has an idea about this issue ?

`# bundle exec rails server
=> Booting Thin
=> Rails 5.2.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /var/lib/gems/2.5.0/gems/less-rails-2.8.0/lib/less/rails/railtie.rb:16)
DEPRECATION WARNING: You are using the a deprecated processor interface Less::Rails::ImportProcessor.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /var/lib/gems/2.5.0/gems/less-rails-2.8.0/lib/less/rails/railtie.rb:21)
Exiting
Traceback (most recent call last):
	73: from bin/rails:4:in `<main>'
	72: from bin/rails:4:in `require'
	71: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
	70: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
	69: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
	68: from /usr/lib/ruby/vendor_ruby/thor.rb:369:in `dispatch'
	67: from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
	66: from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
	65: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:142:in `perform'
	64: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:142:in `tap'
	63: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	62: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:51:in `start'
	61: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
	60: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:354:in `wrapped_app'
	59: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:27:in `app'
	58: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:219:in `app'
	57: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	56: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:40:in `parse_file'
	55: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `new_from_string'
	54: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `eval'
	53: from config.ru:in `<main>'
	52: from config.ru:in `new'
	51: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
	50: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
	49: from config.ru:3:in `block in <main>'
	48: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	47: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	46: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
	45: from /var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	44: from /var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	43: from /home/ubuntu/PINGOWebApp-rails51/config/environment.rb:5:in `<top (required)>'
	42: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
	41: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
	40: from /usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	39: from /usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	38: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	37: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
	36: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
	35: from /usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	34: from /usr/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
	33: from /usr/lib/ruby/2.5.0/tsort.rb:415:in `call'
	32: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `tsort_each_child'
	31: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `each'
	30: from /usr/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	29: from /usr/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
	28: from /usr/lib/ruby/2.5.0/tsort.rb:415:in `call'
	27: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `tsort_each_child'
	26: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `each'
	25: from /usr/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	24: from /usr/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
	23: from /usr/lib/ruby/2.5.0/tsort.rb:415:in `call'
	22: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `tsort_each_child'
	21: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `each'
	20: from /usr/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	19: from /usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	18: from /usr/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	17: from /usr/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	16: from /usr/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	15: from /usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	14: from /usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	13: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
	12: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
	11: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
	10: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:613:in `block in <class:Engine>'
	 9: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:613:in `each'
	 8: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
	 7: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:656:in `load_config_initializer'
	 6: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170:in `instrument'
	 5: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:657:in `block in load_config_initializer'
	 4: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
	 3: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	 2: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
	 1: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
/home/ubuntu/PINGOWebApp-rails51/config/initializers/secret_token.rb:7:in `<top (required)>': undefined local variable or method `config' for main:Object (NameError)
`

**Comment by soumiasari7** [comment]
re Hi, 
i just wanted to update this issue i solved first ptoblem of  DEPRECATION WARNING but now still this message bellow 
if any one can give any suggestion , i need to run it ASAP

`bundle exec rails server
=> Booting Thin
=> Rails 5.2.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options

Exiting Traceback (most recent call last):
	49: from bin/rails:4:in `<main>'
	48: from bin/rails:4:in `require'
	47: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
	46: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
	45: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
	44: from /usr/lib/ruby/vendor_ruby/thor.rb:369:in `dispatch'
	43: from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
	42: from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
	41: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:142:in `perform'
	40: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:142:in `tap'
	39: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	38: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:51:in `start'
	37: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
	36: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:354:in `wrapped_app'
	35: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:27:in `app'
	34: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:219:in `app'
	33: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	32: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:40:in `parse_file'
	31: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `new_from_string'
	30: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `eval'
	29: from config.ru:in `<main>'
	28: from config.ru:in `new'
	27: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
	26: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
	25: from config.ru:3:in `block in <main>'
	24: from /var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	23: from /var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	22: from /home/ubuntu/PINGOWebApp-rails51/config/environment.rb:5:in `<top (required)>'
	21: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
	20: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
	19: from /usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	18: from /usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	17: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	16: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
	15: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
	14: from /usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	13: from /usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	12: from /usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	11: from /usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	10: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
	 9: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
	 8: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
	 7: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/application/bootstrap.rb:81:in `block in <module:Bootstrap>'
	 6: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	 5: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:51:in `each'
	 4: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	 3: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
	 2: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
	 1: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/var/lib/gems/2.5.0/gems/less-rails-2.8.0/lib/less/rails/railtie.rb:15:in `block in <class:Railtie>': uninitialized constant Sprockets::Engines (NameError)
`

**Comment by MichaelWhi** [comment]
did you run `bundle install`? what branch / commit are you using?
