### ISSUE TITLE
isuue with running app on production mode

### ISSUE THREAD

**Issue by soumiasari7** [PingoUPB/PINGOWebApp#23]
Hi ,
i just started with Pingo app and now i wanna run it on production mode but im getting errors i tried :
`RAILS_ENV=production bundle exec rails server`
is there any conf i miss it ?

> Ps: developemnt mode work without problems

**Comment by MichaelWhi** [comment]
what is the error message?

**Comment by soumiasari7** [comment]
@MichaelWhi  thanks for your replying, 
here is message error 
`RAILS_ENV=production bundle exec rails server
=> Booting Thin
=> Rails 5.2.0 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /var/lib/gems/2.5.0/gems/less-rails-2.8.0/lib/less/rails/railtie.rb:16)
DEPRECATION WARNING: You are using the a deprecated processor interface Less::Rails::ImportProcessor.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /var/lib/gems/2.5.0/gems/less-rails-2.8.0/lib/less/rails/railtie.rb:21)
Exiting
Traceback (most recent call last):
	82: from bin/rails:4:in `<main>'
	81: from bin/rails:4:in `require'
	80: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
	79: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
	78: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
	77: from /usr/lib/ruby/vendor_ruby/thor.rb:369:in `dispatch'
	76: from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
	75: from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
	74: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:142:in `perform'
	73: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:142:in `tap'
	72: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	71: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:53:in `start'
	70: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:283:in `start'
	69: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:354:in `wrapped_app'
	68: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:27:in `app'
	67: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:219:in `app'
	66: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	65: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:40:in `parse_file'
	64: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `new_from_string'
	63: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `eval'
	62: from config.ru:in `<main>'
	61: from config.ru:in `new'
	60: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
	59: from /var/lib/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
	58: from config.ru:3:in `block in <main>'
	57: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	56: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	55: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
	54: from /var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	53: from /var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        	52: from /home/ubuntu/AppTestPingo/config/environment.rb:5:in `<top (required)>'
	51: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
	50: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
	49: from /usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	48: from /usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	47: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	46: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
	45: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
	44: from /usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	43: from /usr/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
	42: from /usr/lib/ruby/2.5.0/tsort.rb:415:in `call'
	41: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `tsort_each_child'
	40: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `each'
	39: from /usr/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	38: from /usr/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
	37: from /usr/lib/ruby/2.5.0/tsort.rb:415:in `call'
	36: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `tsort_each_child'
	35: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `each'
	34: from /usr/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	33: from /usr/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
	32: from /usr/lib/ruby/2.5.0/tsort.rb:415:in `call'
	31: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `tsort_each_child'
	30: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `each'
	29: from /usr/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	28: from /usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	27: from /usr/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	26: from /usr/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	25: from /usr/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	24: from /usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	23: from /usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	22: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
	21: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
        	20: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
	19: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:613:in `block in <class:Engine>'
	18: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:613:in `each'
	17: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
	16: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:656:in `load_config_initializer'
	15: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170:in `instrument'
	14: from /var/lib/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:657:in `block in load_config_initializer'
	13: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
	12: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	11: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
	10: from /var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
	 9: from /home/ubuntu/AppTestPingo/config/initializers/redis.rb:2:in `<top (required)>'
	 8: from /home/ubuntu/AppTestPingo/config/initializers/redis.rb:2:in `new'
	 7: from /var/lib/gems/2.5.0/gems/redis-4.0.1/lib/redis.rb:38:in `initialize'
	 6: from /var/lib/gems/2.5.0/gems/redis-4.0.1/lib/redis.rb:38:in `new'
	 5: from /var/lib/gems/2.5.0/gems/redis-4.0.1/lib/redis/client.rb:79:in `initialize'
	 4: from /var/lib/gems/2.5.0/gems/redis-4.0.1/lib/redis/client.rb:403:in `_parse_options'
	 3: from /usr/lib/ruby/2.5.0/uri/common.rb:743:in `URI'
	 2: from /usr/lib/ruby/2.5.0/uri/common.rb:237:in `parse'
	 1: from /usr/lib/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'
/usr/lib/ruby/2.5.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): redis://HOST:port (URI::InvalidURIError)
`
